[package]
name = "neptune"
version = "1.0.0"
edition = "2021"
crate-type = "lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "^0.12.4"