[package]
name = "trident-cli"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neptune = { path = "../neptune" }
requestty = "^0.3.0"